name: Database Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Build the Database Docker image
      run: docker build . --file db.Dockerfile --tag database:$(date +%s)
